## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200

#SearchGuard Config

elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"

searchguard.basicauth.forbidden_usernames: [ "kibanaserver", "logstash", "admin", "elastalert" ]

#searchguard.basicauth.login.brandimage: "http://logo.png"
#searchguard.basicauth.login.title: ""
#searchguard.basicauth.login.subtitle: ""

searchguard.cookie.password: "123567818187654rwrwfsfshdhdhtegdhfzftdhncn"
